name: Type checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    PIP_NO_PYTHON_VERSION_WARNING: 1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true

      - name: Check out project
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache info
        id: pip-cache
        run: |
          echo "dir=$(python -m pip cache dir)" >> $GITHUB_OUTPUT
          echo "py=$(python -c'import sys; print("%d.%d" % sys.version_info[:2])')" >> $GITHUB_OUTPUT

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-py${{ steps.pip-cache.outputs.py }}-${{ hashFiles('setup.cfg') }}
          restore-keys: ${{ runner.os }}-pip-py${{ steps.pip-cache.outputs.py }}-

      - name: Install dependencies
        run: python -m pip install -e .[testing]

      - name: List installed packages
        run: python -m pip list

      - name: Run type checker
        run: python -m mypy --strict --exclude lazy/tests lazy

